name: 'New PR Notification'
on:
  pull_request: 
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-18.04
    steps:
      - name: Send Discord notification
        uses: appleboy/discord-action@master
        with:
          webhook_url: https://discord.com/api/webhooks/1247339572879298561/tBN-O5Bdw4XNsxZPeMPA2YCvRXkZRNslkrxc-rHs03WIt97duIvvVSf6vwWqovhioTIC
          title: New PR opened
          message: "**${{ github.event.pull_request.title }}**\n**Creator:** ${{ github.event.pull_request.user.login }}\n${{ github.event.pull_request.html_url }}"
          include_image: true
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: GitHub PR Notifier
